version: "2.1"
services:
  grocy:
    image: ghcr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/Berlin
    volumes:
      - /Users/christianknedel/docker/grocy/data:/config
    ports:
      - 9283:80
    restart: unless-stopped
